name: adams_county_scheduler
description: A scheduler for Adams County

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  intl: ^0.19.0
  firebase_core: ^2.7.0
  firebase_analytics: ^10.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.10.1
  icons_launcher: ^2.1.0
  flutter_phoenix: ^1.1.0
  retrofit: ^4.0.1
  dio: ^5.0.3
  shared_preferences: ^2.1.0
  firebase_messaging: ^14.4.0
  flutter_local_notifications: ^16.3.0
  dev: ^1.0.0
  auto_size_text: ^3.0.0
  shimmer: ^3.0.0
  share_plus: ^7.2.1
  app_links: ^3.4.5
  package_info_plus: ^5.0.1
  firebase_crashlytics: ^3.3.7
  app_tracking_transparency: ^2.0.4
  flutter_svg: ^2.0.9
  bloc: ^8.1.2
  json_annotation: ^4.8.1
  meta: ^1.9.1
  google_sign_in: ^6.1.6
  collapsible_sidebar: ^2.0.7
  image_picker: ^1.0.5
  firebase_storage: ^11.5.6
  file_picker: ^6.1.1
  flutter_excel: ^1.0.1
  cloud_functions: ^4.6.0
  uuid: ^4.3.3
  universal_html: ^2.2.4
  docx_template: ^0.3.6
  path_provider: ^2.0.13
  permission_handler: ^11.2.0
  fluttertoast: ^8.2.1
  path: ^1.8.2
  provider: ^6.0.5

dependency_overrides:
  archive: 3.4.9
  docx_template: 0.3.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.6.1
  retrofit_generator: ^8.0.6
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

  flutter_lints: ^3.0.1
  test: ^1.24.1


flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/images/png/adams_county.png"
flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # dart run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # dart run flutter_native_splash:remove

  # IMPORTANT NOTE: These parameter do not affect the configuration of Android 12 and later, which
  # handle splash screens differently that prior versions of Android.  Android 12 and later must be
  # configured specifically in the android_12 section below.

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  background_image: "assets/images/png/adams_county.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/templates/student_schedule_template.docx
    - assets/templates/career_attendance_template.docx

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
