name: adams_county_scheduler
description: A scheduler for Adams County

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  app_links: ^6.3.2  # For deep linking
  app_tracking_transparency: ^2.0.4 # For tracking user data
  archive: ^3.5.0 # For zipping and unzipping files
  auto_size_text: ^3.0.0 # For auto sizing text
  bloc: ^9.0.0 # For state management
  cloud_firestore: ^5.4.4 # For firebase cloud firestore
  cloud_functions: ^5.1.3 # For firebase cloud functions
  collapsible_sidebar: ^2.0.7 # For collapsible sidebar
  collection: ^1.18.0 # For collection manipulation
  cupertino_icons: ^1.0.2 # For cupertino icons
  dev: ^1.0.0 # For development
  dio: ^5.0.3 # For http requests
  docx_template: # For docx coversions
    git:
      url: https://github.com/hunterwilhelm/docx_template_dart.git
      commit: 8947449
  firebase_analytics: ^11.3.3 # For firebase analytics
  firebase_core: ^3.6.0 # For firebase core
  firebase_messaging: ^15.1.3 # For firebase messaging
  firebase_storage: ^12.3.4 # For firebase storage
  flutter: # For flutter
    sdk: flutter
  flutter_bloc: ^9.0.0 # For state management
  flutter_local_notifications: ^18.0.0 # For local notifications
  flutter_svg: ^2.0.9 # For svg images

  file_picker: ^9.0.1 # For file picking
  firebase_auth: ^5.3.1 # For firebase authentication
  flutter_excel: ^1.0.1 # For excel files
  flutter_phoenix: ^1.1.0 # For hot reload
  fluttertoast: ^8.2.1 # For toast messages
  google_sign_in: ^6.1.6 # For google sign in
  hive: ^2.2.3 # For local storage
  hive_flutter: ^1.1.0 # For local storage
  intl: ^0.20.2 # For internationalization
  retrofit: ^4.0.1 # For http requests
  icons_launcher: ^3.0.0 # For app icons
  image_picker: ^1.0.5 # For image picking
  json_annotation: ^4.8.1 # For json serialization
  meta: ^1.9.1 # For metadata
  package_info_plus: ^8.1.0 # For package info
  path: ^1.8.2 # For file paths
  path_provider: ^2.0.13 # For file paths
  permission_handler: ^11.2.0 # For permissions
  provider: ^6.0.5 # For state management
  share_plus: ^10.1.1 # For sharing
  shared_preferences: ^2.1.0 # For shared preferences
  shimmer: ^3.0.0 # For shimmer effect
  universal_html: ^2.2.4 # For web support
  uuid: ^4.3.3 # For unique id generation

dev_dependencies:
  build_runner: ^2.3.3 # For building
  flutter_launcher_icons: ^0.14.1 # For app icons
  flutter_lints: ^5.0.0 # For lints
  flutter_test: # For testing
    sdk: flutter
  hive_generator: ^2.0.0 # For local storage
  json_serializable: ^6.6.1 # For json serialization
  retrofit_generator: ^9.1.4 # For http requests
  test: ^1.24.1 # For testing


flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/images/png/adams_county.png"
flutter_native_splash:
  background_image: "assets/images/png/adams_county.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/templates/student_schedule_template.docx
    - assets/templates/career_attendance_template.docx
